### ISSUE TITLE
Windows test don't work

### ISSUE THREAD

**Issue by wwelden** [anewman24/blue-button#3]
![CleanShot 2024-10-24 at 16 47 21@2x](https://github.com/user-attachments/assets/b35193be-3863-4e6e-8807-8a758b859346)

**Comment by anewman24** [comment]
Reason is line 148 in ~/lib/sense.js likely with Windows not resolving the /n characters correctly thus returning "unknown" as type instead of "format_x"

TODO:
find out what whitespace characters are there and how to define them to cover both Windows and other OS

**Comment by anewman24** [comment]
Fixed by normalizing the eol whitespace characters to ensure all were "\n"
